### ISSUE TITLE
【疑问】出入队列是否全局有序？

### ISSUE THREAD

**Issue by FelixHo** [Tencent/phxqueue#1]
找不到提问社区，请允许我在这里提问.

【问题】
请问 "出入队严格有序" 这一个feature指的是 全局队列有序 还是指 单一队列（我的理解就是一个Store）的出入严格有序？如果是后者，要满足全量数据严格有序的话 producer 在入队列的时候就需要做数据倾斜（例如 通过key来约束）？ 谢谢~

**Comment by unixliang** [comment]
你好，
从Store的角度来看单一队列是出入严格有序的，因为一条队列只归属于一个Paxos Group；
但是从Consumer的角度来看默认是相同key出入严格有序，因为Consumer有批量处理特性，其中相同key的数据保证串行处理，不同key的数据会并发处理，这是为了提高消费效率的特性。

**Comment by FelixHo** [comment]
@unixliang 感谢你详细清晰解释~
