### ISSUE TITLE
消息传递语义

### ISSUE THREAD

**Issue by ArvinDevel** [Tencent/phxqueue#15]
您好，对phxqueue的介绍是at-least-once的消息传递语义，且用于业务型消息中间件，那么这个语义是否足够呢？对于支付这样的场景，不应该是exactly-once才可以吗？我个人理解是，phxqueue可靠性做得好，可以保证到达系统的消息完全可靠，只是目前没有对消费状态进行记录，业务应用使用时需要自己维护消费状态来达到exactly-once。请问是这样的吗？

**Comment by unixliang** [comment]
您好，
支付确实需要exactly-once，但是队列在整个支付流程中只是其中一个系统，即使队列完全实现了exactly-once，其它系统也要考虑幂等。既然业务本身需要考虑幂等，队列是at-least-once还是exactly-once就区别不大了。
据我了解，一个消息队列要做到exactly-once，也是要与业务一起配合的，需要做到如下两点：
1. Producer生产支持幂等，这个容易实现；
2. Consumer消费时对业务所做的状态变更，需要与偏移的更新保持同步；Kafka提出了以下两种做法：
2.1. 队列保存业务状态与偏移，保证两者的写是一个原子操作；如果consumer重启了，就取出偏移，作为消费开始位置；这里需要保存在同一个DB里，否则就变成了一个分布式事务，分布式事务的实现依赖队列，变成了先有鸡还是先有蛋的问题；
2.2. 业务保存业务状态与偏移，并提供幂等特性，忽略任何偏移值比存储偏移值小的写入。
