### ISSUE TITLE
安装时候报错，有遇到的嘛？是怎么解决的？谢谢

### ISSUE THREAD

**Issue by yanghonbing** [Tencent/phxqueue#16]
在编译时，我升级了gcc版本到7.2.
make[1]: Leaving directory `/phxqueue/phxqueue/phxqueue_phxrpc/app/scheduler'
g++ -std=c++11 -Wall -D_REENTRANT -D_GNU_SOURCE -D_XOPEN_SOURCE -fPIC -m64 -I/phxqueue/phxqueue//third_party/protobuf/include -O2 -I/phxqueue/phxqueue/ -I/phxqueue/phxqueue//third_party/glog/include -I/phxqueue/phxqueue//third_party/protobuf/include -I/phxqueue/phxqueue//third_party/leveldb/include -I/phxqueue/phxqueue//third_party/colib -I/phxqueue/phxqueue//third_party/phxpaxos/include -I/phxqueue/phxqueue//third_party/phxpaxos/include -I/phxqueue/phxqueue//third_party/phxrpc -I/phxqueue/phxqueue//third_party/phxpaxos/plugin/include -I/phxqueue/phxqueue//phxqueue_phxrpc/test/ -c phxqueue_phxrpc/test/test_rpc_config.cpp -o phxqueue_phxrpc/test/test_rpc_config.o
In file included from /phxqueue/phxqueue/phxqueue/comm.h:16:0,
                 from /phxqueue/phxqueue/phxqueue/./config/baseconfig.h:18,
                 from /phxqueue/phxqueue/phxqueue/config.h:15,
                 from /phxqueue/phxqueue/phxqueue/test/test_config.h:15,
                 from phxqueue_phxrpc/test/test_rpc_config.h:15,
                 from phxqueue_phxrpc/test/test_rpc_config.cpp:13:
/phxqueue/phxqueue/phxqueue/./comm/logger.h:48:22: error: ‘function’ in namespace ‘std’ does not name a template type
 using LogFunc = std::function<void (const int, const char *, va_list)>;
                      ^~~~~~~~
/phxqueue/phxqueue/phxqueue/./comm/logger.h:67:21: error: ‘LogFunc’ has not been declared
     void SetLogFunc(LogFunc log_func);
                     ^~~~~~~
In file included from /phxqueue/phxqueue/phxqueue/comm.h:18:0,
                 from /phxqueue/phxqueue/phxqueue/./config/baseconfig.h:18,
                 from /phxqueue/phxqueue/phxqueue/config.h:15,
                 from /phxqueue/phxqueue/phxqueue/test/test_config.h:15,
                 from phxqueue_phxrpc/test/test_rpc_config.h:15,
                 from phxqueue_phxrpc/test/test_rpc_config.cpp:13:
/phxqueue/phxqueue/phxqueue/./comm/masterclient.h:64:30: error: ‘std::function’ has not been declared
                         std::function<RetCode (Req &, Resp &)> rpc_func) {
                              ^~~~~~~~
/phxqueue/phxqueue/phxqueue/./comm/masterclient.h:64:38: error: expected ‘,’ or ‘...’ before ‘<’ token
                         std::function<RetCode (Req &, Resp &)> rpc_func) {
                                      ^
In file included from /phxqueue/phxqueue/phxqueue/plugin.h:17:0,
                 from /phxqueue/phxqueue/phxqueue_phxrpc/./plugin/configfactory.h:18,
                 from /phxqueue/phxqueue/phxqueue_phxrpc/plugin.h:15,
                 from phxqueue_phxrpc/test/test_rpc_config.cpp:18:
/phxqueue/phxqueue/phxqueue/./plugin/logger_google.h:29:60: error: ‘phxqueue::comm::LogFunc’ has not been declared
                          const int google_log_level, comm::LogFunc &log_func);
                                                            ^~~~~~~
In file included from /phxqueue/phxqueue/phxqueue/plugin.h:18:0,
                 from /phxqueue/phxqueue/phxqueue_phxrpc/./plugin/configfactory.h:18,
                 from /phxqueue/phxqueue/phxqueue_phxrpc/plugin.h:15,
                 from phxqueue_phxrpc/test/test_rpc_config.cpp:18:
/phxqueue/phxqueue/phxqueue/./plugin/logger_sys.h:28:111: error: ‘phxqueue::comm::LogFunc’ has not been declared
     static int GetLogger(const std::string &module_name, const int sys_log_level, const bool daemonize, comm::LogFunc &pLogFunc);
                                                                                                               ^~~~~~~
make: *** [phxqueue_phxrpc/test/test_rpc_config.o] Error 1

**Comment by unixliang** [comment]
你好，g++的版本是多少？

**Comment by yanghonbing** [comment]
[root@test third_party]# g++ --version
g++ (GCC) 7.2.0

**Comment by unixliang** [comment]
```
/phxqueue/phxqueue/phxqueue/./comm/logger.h:48:22: error: ‘function’ in namespace ‘std’ does not name a template type
```

看着像是编译器不支持c++11，试试写个简单的c++11例子编译看看？
