### ISSUE TITLE
没有C的api吗？

### ISSUE THREAD

**Issue by tinyshu** [Tencent/phxqueue#18]
没有C的api吗？现在如何使用了？  编译，运行，测试工具都ok了

**Comment by tinyshu** [comment]
是参考那几个test工具来搞吗

**Comment by unixliang** [comment]
你好，暂时只有C++的API。
其它语言会尽快跟上：）

**Comment by tinyshu** [comment]
是参考test_store_main.cpp 吗？

**Comment by unixliang** [comment]
入队API请参考test_producer_echo_main.cpp

**Comment by unixliang** [comment]
#12
