### ISSUE TITLE
使用test_producer_echo_main发送了3个消息，3个consumer_main都没有输出

### ISSUE THREAD

**Issue by tinyshu** [Tencent/phxqueue#21]
使用test_producer_echo_main发送了3个消息，3个consumer_main都没有输出
都部署在同一台机器上
使用test_producer_echo_main发送三个消息都消息成功 
[root@iZuf6hx16c6lym9fxx51xcZ phxqueue]# bin/test_producer_echo_main
produce echo "Pisz1QF7YK" succeeded!
[root@iZuf6hx16c6lym9fxx51xcZ phxqueue]# bin/test_producer_echo_main
produce echo "yGGtFBHAjL" succeeded!
[root@iZuf6hx16c6lym9fxx51xcZ phxqueue]# bin/test_producer_echo_main
produce echo "Re3r9t3xT1" succeeded!

**consumer_main1**
bin/consumer_main -c etc/consumer_server.0.conf
consume echo "VDPvMIUOgC" succeeded! sub_id 1 store_id 1 queue_id 29 item_uin 0
consume echo "cZdWvCi3SZ" succeeded! sub_id 1 store_id 1 queue_id 72 item_uin 0
consume echo "3V0CzqjvvV" succeeded! sub_id 1 store_id 1 queue_id 64 item_uin 0
consume echo "BnA6CDEN6j" succeeded! sub_id 1 store_id 1 queue_id 36 item_uin 0
consume echo "XpaVZfuI7w" succeeded! sub_id 1 store_id 1 queue_id 96 item_uin 0

**consumer_main1**
 bin/consumer_main -c etc/consumer_server.1.conf
consume echo "0lcDFvKgAJ" succeeded! sub_id 1 store_id 1 queue_id 24 item_uin 0

**consumer_main2**
cd tiny/queue/phxqueue/
[root@iZuf6hx16c6lym9fxx51xcZ phxqueue]# bin/consumer_main -c etc/consumer_server.2.conf

**Comment by unixliang** [comment]
c89958854a0b67d19843c2c5d89a02791b9e060c
Fixed。请pull以上commit后重试。
原因是样例配置有误，导致3个consumer用了同一块共享内存。共享内存里保存的是consumer到队列的处理关系，所以3个consumer处理了同一批队列，导致部分队列没有consumer消费。

**Comment by tinyshu** [comment]
@unixliang   git pull后也编译现了，现在连消息都收不到了

**Comment by unixliang** [comment]
方便打包日志发送到 phxteam@tencent.com 吗？

**Comment by tinyshu** [comment]
已经发送log到 phxteam邮箱了

**Comment by unixliang** [comment]
```
$ grep 'ChildRun' consumer.0/*
consumer.0/test.iZuf6hx16c6lym9fxx51xcZ.root.log.INFO.20170916-203731.12931:I0916 20:37:31.094595 12931 logger_google.cpp:73]  INFO: PN8phxqueue8consumer8ConsumerE::ChildRun:481 INFO: start vpid 0
consumer.0/test.iZuf6hx16c6lym9fxx51xcZ.root.log.INFO.20170916-203731.12932:I0916 20:37:31.094126 12932 logger_google.cpp:73]  INFO: PN8phxqueue8consumer8ConsumerE::ChildRun:481 INFO: start vpid 1
$ grep 'ChildRun' consumer.1/*
consumer.1/test.iZuf6hx16c6lym9fxx51xcZ.root.log.INFO.20170916-203746.12938:I0916 20:37:46.119879 12938 logger_google.cpp:73]  INFO: PN8phxqueue8consumer8ConsumerE::ChildRun:481 INFO: start vpid 0
consumer.1/test.iZuf6hx16c6lym9fxx51xcZ.root.log.INFO.20170916-203746.12939:I0916 20:37:46.119526 12939 logger_google.cpp:73]  INFO: PN8phxqueue8consumer8ConsumerE::ChildRun:481 INFO: start vpid 1
$ grep 'ChildRun' consumer.2/*
consumer.2/test.iZuf6hx16c6lym9fxx51xcZ.root.log.INFO.20170916-203750.12946:I0916 20:37:50.740314 12946 logger_google.cpp:73]  INFO: PN8phxqueue8consumer8ConsumerE::ChildRun:481 INFO: start vpid 1
```

从日志看来，consumer.2有一个进程没启动（vpid 0）。
麻烦贴一下dmesg信息，重启consumer.2试试。

**Comment by unixliang** [comment]
在我的环境中，kill掉任何一个处理进程（例如vpid 0），其父进程都会拉起新进程并继续处理，应该是符合设计预期的。

**Comment by tinyshu** [comment]
[root@iZuf6hx16c6lym9fxx51xcZ ~]# ps -ef | grep consumer_main            
root     12928  9248  0 20:37 pts/1    00:00:00 bin/consumer_main -c etc/consumer_server.0.conf
root     12929 12928  0 20:37 pts/1    00:00:00 bin/consumer_main -c etc/consumer_server.0.conf
root     12930 12928  0 20:37 pts/1    00:00:00 bin/consumer_main -c etc/consumer_server.0.conf
root     12931 12928  0 20:37 pts/1    00:00:14 bin/consumer_main -c etc/consumer_server.0.conf
root     12932 12928  0 20:37 pts/1    00:00:15 bin/consumer_main -c etc/consumer_server.0.conf
root     12935  9380  0 20:37 pts/2    00:00:00 bin/consumer_main -c etc/consumer_server.1.conf
root     12936 12935  0 20:37 pts/2    00:00:00 bin/consumer_main -c etc/consumer_server.1.conf
root     12937 12935  0 20:37 pts/2    00:00:00 bin/consumer_main -c etc/consumer_server.1.conf
root     12938 12935  0 20:37 pts/2    00:00:14 bin/consumer_main -c etc/consumer_server.1.conf
root     12939 12935  0 20:37 pts/2    00:00:14 bin/consumer_main -c etc/consumer_server.1.conf
root     12942  9516  0 20:37 pts/3    00:00:00 bin/consumer_main -c etc/consumer_server.2.conf
root     12943 12942  0 20:37 pts/3    00:00:00 bin/consumer_main -c etc/consumer_server.2.conf
root     12944 12942  0 20:37 pts/3    00:00:00 bin/consumer_main -c etc/consumer_server.2.conf
root     12945 12942  0 20:37 pts/3    00:00:14 bin/consumer_main -c etc/consumer_server.2.conf
root     12946 12942  0 20:37 pts/3    00:00:14 bin/consumer_main -c etc/consumer_server.2.conf

vpid 0是什么了？  我ps看到consumer_main 在运行啊

**Comment by tinyshu** [comment]
@unixliang 又重启了一次好像可以了
