### ISSUE TITLE
你的程序要求必须是ssd磁盘？我在普通机器上启动完成，iowait都70-90%

### ISSUE THREAD

**Issue by zhaozhihua2008** [Tencent/phxqueue#23]
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
                     1.01    0.00    1.13   72.36    0.00   25.50

[xdpp@tpd2 ~]$ ps -ef|grep store
xdpp      8816     1  4 02:01 ?        00:01:17 bin/store_main -c etc/store_server.0.conf -d
xdpp      8818     1  4 02:01 ?        00:01:16 bin/store_main -c etc/store_server.1.conf -d
xdpp      8820     1  2 02:01 ?        00:00:42 bin/store_main -c etc/store_server.2.conf -d
root     13015     1  0 Aug02 ?        00:00:00 /usr/libexec/tracker-store
xdpp     14411 13913  0 02:28 pts/1    00:00:00 grep --color=auto store

杀了进程就好了。
[xdpp@tpd2 ~]$ kill -9 8816 8818 8820 
[xdpp@tpd2 ~]$ iostat 2 2
Linux 3.10.0-514.el7.x86_64 (tpd2)      09/17/2017      _x86_64_        (8 CPU)

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
                       0.48    0.00    0.25    0.08    0.00   99.20

**Comment by unixliang** [comment]
你好，
我们在 c899588 中修改了sample配置，减少了队列数，尽可能减低sample运行门槛。
另外phxqueue建议运行在SSD上，原因是目前为了保证多个paxos实例的存储隔离，写入时没有做WAL，在机器硬盘上随机写比例高，性能不好。
