### ISSUE TITLE
build failover on MacOS sierra

### ISSUE THREAD

**Issue by bighunter513** [Tencent/phxqueue#24]
first issue is compile glog failed, I mannually update glog to 0.3.4 fixed,
but then encounter following error:

ar -cvq /Users/xxx/phxqueue/third_party/phxpaxos/.lib/libphxpaxos.a
ar: no archive members specified

**Comment by unixliang** [comment]
The reason of failure is clang ++ does not support empty static library generation. There is still lots of work to be done in mac build support. It is recommended to build in linux docker on mac.
