### ISSUE TITLE
程序运行经常出现core: std::system_error

### ISSUE THREAD

**Issue by guyannanfei25** [Tencent/phxqueue#25]
Hi，运行过程中碰到以下几个问题：
1，程序运行有概率出现core：
root@survey phxqueue [master] $ bin/store_main -c etc/store_server.0.conf
terminate called after throwing an instance of 'std::system_error'
  what():  
已放弃 (core dumped)
root@survey phxqueue [master] $ bin/store_main -c etc/store_server.0.conf
server already started, 1 io threads 10 workers
listen succ, ip 127.0.0.1 port 5100

root@survey phxqueue [master] $ bin/store_main -c etc/store_server.1.conf
server already started, 1 io threads 10 workers
listen succ, ip 127.0.0.1 port 5200
terminate called after throwing an instance of 'std::system_error'
  what():  
已放弃 (core dumped)

2，集群模式，即使启动三个store也会出现paxos_ret 404
E0918 11:27:23.969184 12420 logger_google.cpp:79]  ERR: PN8phxqueue4lock16KeepMasterThreadE::KeepMaster:257 MASTERSTAT: ERR: Propose err. paxos_ret 404 paxos_group_id 30 buf.length 20 
I0918 11:27:23.969236 12420 logger_google.cpp:73]  INFO: PN8phxqueue4lock16KeepMasterThreadE::KeepMaster:238 MASTERSTAT: begin try to get back master. paxos_group_id 33 master_rate 100 
I0918 11:27:24.850062 12419 logger_google.cpp:73]  INFO: PN8phxqueue4lock11CleanThreadE::DoRun:120 now 1180022589 nr_key 0 nr_clean_key 0 
E0918 11:27:25.258280 12423 logger_google.cpp:79]  ERR: PN8phxqueue4lock4LockE::GetLockInfo:269 paxos_group 34 lock "1000-1-1-0" CheckMaster err 10105 
E0918 11:27:25.258319 12423 logger_google.cpp:79]  ERR: P15LockServiceImpl::GetLockInfo:42 Lock GetLockInfo err 10105 
E0918 11:27:25.469329 12420 logger_google.cpp:79]  ERR: PN8phxqueue4lock16KeepMasterThreadE::KeepMaster:257 MASTERSTAT: ERR: Propose err. paxos_ret 404 paxos_group_id 33 buf.length 20 
I0918 11:27:25.469388 12420 logger_google.cpp:73]  INFO: PN8phxqueue4lock16KeepMasterThreadE::KeepMaster:238 MASTERSTAT: begin try to get back master. paxos_group_id 36 master_rate 100 
I0918 11:27:25.850183 12419 logger_google.cpp:73]  INFO: PN8phxqueue4lock11CleanThreadE::DoRun:120 now 1180023589 nr_key 0 nr_clean_key 0 
I0918 11:27:26.850322 12419 logger_google.cpp:73]  INFO: PN8phxqueue4lock11CleanThreadE::DoRun:120 now 1180024589 nr_key 0 nr_clean_key 0 
E0918 11:27:26.969480 12420 logger_google.cpp:79]  ERR: PN8phxqueue4lock16KeepMasterThreadE::KeepMaster:257 MASTERSTAT: ERR: Propose err. paxos_ret 404 paxos_group_id 36 buf.length 20 
I0918 11:27:26.969521 12420 logger_google.cpp:73]  INFO: PN8phxqueue4lock16KeepMasterThreadE::KeepMaster:238 MASTERSTAT: begin try to get back master. paxos_group_id 39 master_rate 100 
E0918 11:27:27.258903 12424 logger_google.cpp:79]  ERR: PN8phxqueue4lock4LockE::GetLockInfo:269 paxos_group 34 lock "1000-1-1-0" CheckMaster err 10105 
E0918 11:27:27.258942 12424 logger_google.cpp:79]  ERR: P15LockServiceImpl::GetLockInfo:42 Lock GetLockInfo err 10105 
I0918 11:27:27.850438 12419 logger_google.cpp:73]  INFO: PN8phxqueue4lock11CleanThreadE::DoRun:120 now 1180025589 nr_key 0 nr_clean_key 0 

3，启动三个store服务之后，lock[0-1]能正常启动，lock2服务无法启动，日志如下：
0918 11:30:01.655338 13173 logger_google.cpp:79]  ERR: PN8phxqueue4lock7LockMgrE::Init:111 topic_id 1000 paxos_group_id 24 ReadCheckpoint not exist 
E0918 11:30:01.655375 13173 logger_google.cpp:79]  ERR: PN8phxqueue4lock7LockMgrE::ReadRestartCheckpoint:240 topic_id 1000 paxos_group_id 24 not exist 
E0918 11:30:01.655387 13173 logger_google.cpp:79]  ERR: PN8phxqueue4lock7LockMgrE::Init:127 topic_id 1000 paxos_group_id 24 ReadRestartCheckpoint not exist 
I0918 11:30:01.655407 13173 logger_google.cpp:73]  INFO: Init:134 topic_id 1000 paxos_group_id 24 cp 18446744073709551615 restart_cp 18446744073709551615 
E0918 11:30:04.663666 13173 logger_google.cpp:79]  ERR: PN8phxqueue4lock7LockMgrE::ReadCheckpoint:188 topic_id 1000 paxos_group_id 25 not exist 
E0918 11:30:04.663712 13173 logger_google.cpp:79]  ERR: PN8phxqueue4lock7LockMgrE::Init:111 topic_id 1000 paxos_group_id 25 ReadCheckpoint not exist 
E0918 11:30:04.663734 13173 logger_google.cpp:79]  ERR: PN8phxqueue4lock7LockMgrE::ReadRestartCheckpoint:240 topic_id 1000 paxos_group_id 25 not exist 
E0918 11:30:04.663753 13173 logger_google.cpp:79]  ERR: PN8phxqueue4lock7LockMgrE::Init:127 topic_id 1000 paxos_group_id 25 ReadRestartCheckpoint not exist 
I0918 11:30:04.663794 13173 logger_google.cpp:73]  INFO: Init:134 topic_id 1000 paxos_group_id 25 cp 18446744073709551615 restart_cp 18446744073709551615 
E0918 11:30:04.817548 13173 logger_google.cpp:79]  ERR: PN8phxqueue4lock7LockMgrE::ReadCheckpoint:188 topic_id 1000 paxos_group_id 26 not exist 
E0918 11:30:04.817597 13173 logger_google.cpp:79]  ERR: PN8phxqueue4lock7LockMgrE::Init:111 topic_id 1000 paxos_group_id 26 ReadCheckpoint not exist 
E0918 11:30:04.817615 13173 logger_google.cpp:79]  ERR: PN8phxqueue4lock7LockMgrE::ReadRestartCheckpoint:240 topic_id 1000 paxos_group_id 26 not exist 
E0918 11:30:04.817625 13173 logger_google.cpp:79]  ERR: PN8phxqueue4lock7LockMgrE::Init:127 topic_id 1000 paxos_group_id 26 ReadRestartCheckpoint not exist 
I0918 11:30:04.817636 13173 logger_google.cpp:73]  INFO: Init:134 topic_id 1000 paxos_group_id 26 cp 18446744073709551615 restart_cp 18446744073709551615 
E0918 11:30:05.590431 13173 logger_google.cpp:79]  ERR: PN8phxqueue4lock7LockMgrE::ReadCheckpoint:188 topic_id 1000 paxos_group_id 27 not exist 
E0918 11:30:05.590472 13173 logger_google.cpp:79]  ERR: PN8phxqueue4lock7LockMgrE::Init:111 topic_id 1000 paxos_group_id 27 ReadCheckpoint not exist 
E0918 11:30:05.590493 13173 logger_google.cpp:79]  ERR: PN8phxqueue4lock7LockMgrE::ReadRestartCheckpoint:240 topic_id 1000 paxos_group_id 27 not exist 
E0918 11:30:05.590504 13173 logger_google.cpp:79]  ERR: PN8phxqueue4lock7LockMgrE::Init:127 topic_id 1000 paxos_group_id 27 ReadRestartCheckpoint not exist 
I0918 11:30:05.590515 13173 logger_google.cpp:73]  INFO: Init:134 topic_id 1000 paxos_group_id 27 cp 18446744073709551615 restart_cp 18446744073709551615 
E0918 11:30:06.642740 13173 logger_google.cpp:79]  ERR: PN8phxqueue4lock7LockMgrE::ReadCheckpoint:188 topic_id 1000 paxos_group_id 28 not exist 
E0918 11:30:06.642802 13173 logger_google.cpp:79]  ERR: PN8phxqueue4lock7LockMgrE::Init:111 topic_id 1000 paxos_group_id 28 ReadCheckpoint not exist 
E0918 11:30:06.642829 13173 logger_google.cpp:79]  ERR: PN8phxqueue4lock7LockMgrE::ReadRestartCheckpoint:240 topic_id 1000 paxos_group_id 28 not exist 
E0918 11:30:06.642849 13173 logger_google.cpp:79]  ERR: PN8phxqueue4lock7LockMgrE::Init:127 topic_id 1000 paxos_group_id 28 ReadRestartCheckpoint not exist 
I0918 11:30:06.642868 13173 logger_google.cpp:73]  INFO: Init:134 topic_id 1000 paxos_group_id 28 cp 18446744073709551615 restart_cp 18446744073709551615 

还有就是几个服务运行在一个docker中，确实非常占资源，机械硬盘的机器上负载瞬间飙到300+

**Comment by unixliang** [comment]
你好，

> 程序运行有概率出现core

日志处理逻辑的确有问题，会导致非法内存访问，目前已fix，详见 60416c1

> 集群模式，即使启动三个store也会出现paxos_ret 404

> 启动三个store服务之后，lock[0-1]能正常启动，lock2服务无法启动

你贴的是lock的日志。三个lock/store从无到有的启动过程中，会有一段时间的选举期，之后应该是稳定的，没有错误日志。如果错误日志持续，烦请打包日志发到 phxteam@tencent.com

> 还有就是几个服务运行在一个docker中，确实非常占资源，机械硬盘的机器上负载瞬间飙到300+

确实。所以我们在 c89958854a0b67d19843c2c5d89a02791b9e060c 中修改了sample配置，减少了队列数，尽可能减低sample运行门槛。
另外phxqueue建议运行在SSD上，原因是目前为了保证多个paxos实例的存储隔离，写入时没有做WAL，在机器硬盘上随机写比例高，性能不好。
