### ISSUE TITLE
执行 bash build.sh 时报错

### ISSUE THREAD

**Issue by yufei2999** [Tencent/phxqueue#26]
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I./src -I./src -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -DNO_FRAME_POINTER -DNDEBUG -fPIC -MT libglog_la-demangle.lo -MD -MP -MF .deps/libglog_la-demangle.Tpo -c src/demangle.cc  -fPIC -DPIC -o .libs/libglog_la-demangle.o
src/demangle.cc: In function 'bool google::AtLeastNumCharsRemaining(const char*, int)':
src/demangle.cc:170:16: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
     if (str == '\0') {
                ^~~~
src/demangle.cc: In function 'bool google::ParseCharClass(google::State*, const char*)':
src/demangle.cc:226:29: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
   if (state->mangled_cur == '\0') {
                             ^~~~
make: *** [libglog_la-demangle.lo] Error 1
glog install fail. please check compile error info.

**Comment by unixliang** [comment]
你好，请参考以下办法解决。

<https://github.com/google/glog/issues/52>

```
I have been same error and I tried following command on Ubuntu 14.04. It did work.
cd glog
mkdir build && cd build
export CXXFLAGS="-fPIC" && cmake .. && make VERBOSE=1
make
sudo make install
```

**Comment by dingxiangfei2009** [comment]
No, maybe bump `glog` to at least `v0.3.4` and avoid `v0.3.3` as much as you can.
The compilation error is simply because the code wasn't written properly. It made no sense at all.
