### ISSUE TITLE
store_main执行时报错。

### ISSUE THREAD

**Issue by gxnokia** [Tencent/phxqueue#27]
[root@localhost phxqueue]# bin/store_main -c etc/store_server.0.conf
ERR: MakeArgs ret -1

版本如下：
[root@localhost phxqueue]# git log
commit c89958854a0b67d19843c2c5d89a02791b9e060c
Author: unixliang <junjieliang@qq.com>
Date:   Sat Sep 16 11:21:41 2017 +0000

    set different shm_key to each consumer

**Comment by unixliang** [comment]
你好，
麻烦贴出store的日志，或者打包日志发到phxteam@tencent.com。
