### ISSUE TITLE
test_store_main问题

### ISSUE THREAD

**Issue by tinyshu** [Tencent/phxqueue#28]
test_producer_echo_main发送消息 ，消费者可能收到 ，为什么test_store_main不行，代码如下

**test_store_main.cpp**
int main(int argc, char ** argv) {
	phxqueue::comm::LogFunc log_func;
	phxqueue::plugin::LoggerGoogle::GetLogger("test_producer", "/tmp/phxqueue/log", 3, log_func);

	const string global_config_path("./etc/globalconfig.conf");

    phxqueue::plugin::ConfigFactory::SetConfigFactoryCreateFunc(
		[global_config_path]()->unique_ptr < phxqueue::plugin::ConfigFactory > {
		return unique_ptr<phxqueue::plugin::ConfigFactory>(
			new phxqueue_phxrpc::plugin::ConfigFactory(global_config_path));
	});

	phxqueue::producer::ProducerOption opt;
    opt.log_func = log_func;

	phxqueue::test::SimpleProducer producer(opt);
    producer.Init();
	
	string buf = "buffer";
	//producer.Enqueue(1000, 123, 1, "buffer", 1);
	phxqueue::comm::RetCode ret = producer.Enqueue(1000, 0, 3, buf, 1);
	//phxqueue::comm::RetCode ret{producer->Enqueue(topic_id, uin, handle_id, buf, pub_id)};
	if (phxqueue::comm::RetCode::RET_OK == ret) 
	{
		printf("produce echo \"%s\" succeeded!\n", buf.c_str());
		fflush(stdout);
	}
	else {
		printf("produce echo \"%s\" failed return %d!\n", buf.c_str(), phxqueue::comm::as_integer(ret));
		fflush(stdout);
	}

    return 0;
}

**test_producer_echo_main代码**
int main(int argc, char **argv) {
    const char *module_name{program_invocation_short_name};

    if (argc < 1) {
        ShowUsage(module_name);
    }

    const string global_config_path("./etc/globalconfig.conf");

    phxqueue::plugin::ConfigFactory::SetConfigFactoryCreateFunc(
            [global_config_path]()->unique_ptr<phxqueue::plugin::ConfigFactory> {
                return unique_ptr<phxqueue::plugin::ConfigFactory>(
                        new phxqueue_phxrpc::plugin::ConfigFactory(global_config_path));
            });

    constexpr uint32_t len{10};
    char random_str[len + 1]{'\0'};
    GenRandomString(random_str, len);
    string buf(random_str);

    phxqueue::producer::ProducerOption opt;
    unique_ptr<phxqueue::producer::Producer> producer;
    producer.reset(new phxqueue_phxrpc::producer::Producer(opt));
    producer->Init();

    const int topic_id{1000};   //主题id
    const uint64_t uin{0};      //业务层的key,相同的key入同一个队列 
    const int handle_id{3};    //这个消息被订阅者接受后，那个上层回调函数处理
    const int pub_id{1};       //topicinfo里的pubs段，这个段指定发布者和订阅者的关系

    phxqueue::comm::RetCode ret{producer->Enqueue(topic_id, uin, handle_id, buf, pub_id)};

    if (phxqueue::comm::RetCode::RET_OK == ret) {
        printf("produce echo \"%s\" succeeded!\n", buf.c_str());
        fflush(stdout);
    } else {
        printf("produce echo \"%s\" failed return %d!\n", buf.c_str(), phxqueue::comm::as_integer(ret));
        fflush(stdout);
    }

    return 0;
}

2个代码我做了一下修改，没什么区别，可是test_store_main发送消息返回成功，但是消费者没有收到

**Comment by unixliang** [comment]
```handle_id``` 需要填2。

这个值是在```phxqueue_phxrpc/test/consumer_main.cpp```里确定的：

```
    const int simple_handle_id{1};
    const int echo_handle_id{2};   <----- 2表示echo
    phxqueue_phxrpc::consumer::Consumer consumer(opt);
    consumer.AddHandlerFactory(simple_handle_id,
            new phxqueue::comm::DefaultHandlerFactory<phxqueue::test::SimpleHandler>());
    consumer.AddHandlerFactory(echo_handle_id,
            new phxqueue::comm::DefaultHandlerFactory<phxqueue_phxrpc::test::EchoHandler>());
    consumer.Run();
```
