### ISSUE TITLE
为什么test_producer_echo_main发送的消息都是consume2收到

### ISSUE THREAD

**Issue by tinyshu** [Tencent/phxqueue#30]
测试列子，开启了2个消费者，，收到消息的总是consume2，这个拉取策略是怎么样的，为什么其他2个consume获取不到消息 @unixliang

**Comment by unixliang** [comment]
你好，
为了确保顺序性，一个队列只会被一个consumer进程处理；而sample为了尽量简单，只配置了一个队列；根据一致性hash的结果，是由consumer2来负责处理的，所以只有consumer2有处理日志。

**Comment by tinyshu** [comment]
谢谢解答，还有个问题 producer.Enqueue的uin参数来做hash的吗？ test_producer_echo_main我修改过，每次我传入的uin都不一样，都是被consumer2消费了 ，如果不是用uin那队列和consumer是如何对应的了

**Comment by unixliang** [comment]
> producer.Enqueue的uin参数来做hash的吗？


是的，uin决定了请求会入队到哪个队列。

> test_producer_echo_main我修改过，每次我传入的uin都不一样，都是被consumer2消费了 ，如果不是用uin那队列和consumer是如何对应的了

因为sample只配置了一个队列，所以无论怎么hash，都是那条队列。
可以尝试改```topicconfig.conf```的```ranges```配置项，多配一些队列，例如```"ranges": ["0-1"]```
