### ISSUE TITLE
queue_info_id的ranges和consumers关系问题

### ISSUE THREAD

**Issue by tinyshu** [Tencent/phxqueue#31]
如下配置 ，ranges": ["0-3"] (这个好像会有4个队列0-4)，，我开始的3个consumer，，，，
{
    "consumers":
    [
        {
            "addr":
            {
                "ip": "127.0.0.1",
                "port": "8001"
            },
            "scale": "1000",
            "sub_ids": [1]
        },
        
       {
            "addr":
            {
                "ip": "127.0.0.1",
                "port": "8002"
            },
            "scale": "1000",
            "sub_ids": [1]
        },

        {
            "addr":
            {
                "ip": "127.0.0.1",
                "port": "8002"
            },
            "scale": "1000",
            "sub_ids": [1]
        }
    ]
}

{
    "topic":
    {
        "topic_id": "1000",
        "handle_ids": ["1", "2","3"],
        "store_paxos_batch_count": "80",
        "store_paxos_batch_delay_time_ms": "30"
    },
    "queue_infos":
    [
        {
            "queue_info_id": "1",
            "ranges": ["0-2"]
        }
    ],
    "pubs":
    [
        {
            "pub_id": "1",
            "sub_ids": ["1"],
            "queue_info_ids": ["1"]
        }
    ],
    "subs":
    [
        {
            "sub_id": "1",
            "use_dynamic_scale": "0",
            "skip_lock": "1"
        }
    ]
}

**看如下输出**
**[root@iZuf6hx16c6lym9fxx51xcZ phxqueue]# bin/consumer_main -c etc/consumer_server.0.conf**

mytest consume echo "2J0w4ZrKeX" succeeded! sub_id 1 store_id 1 queue_id 3 item_uin 0
mytest consume echo "9eB7fb94CU" succeeded! sub_id 1 store_id 1 queue_id 3 item_uin 8
mytest consume echo "8i39WwoEkw" succeeded! sub_id 1 store_id 1 queue_id 0 item_uin 9
mytest consume echo "BbJIVJ3Yqt" succeeded! sub_id 1 store_id 1 queue_id 3 item_uin 11
**mytest consume echo "WpMK6SnRtp" succeeded! sub_id 1 store_id 1 queue_id 0 item_uin 12**
mytest consume echo "ioE7Bg456h" succeeded! sub_id 1 store_id 1 queue_id 3 item_uin 13
mytest consume echo "dKqiyFQ8n4" succeeded! sub_id 1 store_id 1 queue_id 3 item_uin 14
mytest consume echo "s38ipUniO6" succeeded! sub_id 1 store_id 1 queue_id 0 item_uin 15

**[root@iZuf6hx16c6lym9fxx51xcZ phxqueue]# bin/consumer_main -c etc/consumer_server.1.conf**

mytest consume echo "GCaOQhrNPS" succeeded! sub_id 1 store_id 1 queue_id 2 item_uin 1
mytest consume echo "dxNsISq4jT" succeeded! sub_id 1 store_id 1 queue_id 2 item_uin 2
mytest consume echo "NwvNzdHAWA" succeeded! sub_id 1 store_id 1 queue_id 1 item_uin 3
mytest consume echo "rSSiLJx6Js" succeeded! sub_id 1 store_id 1 queue_id 2 item_uin 4
mytest consume echo "HP9dWvvXYQ" succeeded! sub_id 1 store_id 1 queue_id 1 item_uin 5
mytest consume echo "SOnE40mUf0" succeeded! sub_id 1 store_id 1 queue_id 1 item_uin 6
mytest consume echo "xBEWX56qMe" succeeded! sub_id 1 store_id 1 queue_id 2 item_uin 7

**[root@iZuf6hx16c6lym9fxx51xcZ phxqueue]# bin/consumer_main -c etc/consumer_server.2.conf**

mytest consume echo "HZgJqPTrpf" succeeded! sub_id 1 store_id 1 queue_id 0 item_uin 10
**mytest consume echo "WpMK6SnRtp" succeeded! sub_id 1 store_id 1 queue_id 0 item_uin 12**
mytest consume echo "s38ipUniO6" succeeded! sub_id 1 store_id 1 queue_id 0 item_uin 15

1.有下面几个问题 consumer是怎么和队列对应的，还是各个consumer抢占拉取数据没有对应关系
2.为什么有些记录会被2个consumer消费，比如mytest consume echo "WpMK6SnRtp" succeeded! sub_id 1 store_id 1 queue_id 0 item_uin 12 ，，在consumer0和consumer2都有输出

**Comment by unixliang** [comment]
> consumer是怎么和队列对应的，还是各个consumer抢占拉取数据没有对应关系

在不部署scheduler的情况下，(sub_id, store_id, queue_id)三元组到consumer的对应关系是固定的，前者只对应一个consumer。

> 为什么有些记录会被2个consumer消费，比如mytest consume echo "WpMK6SnRtp" succeeded! sub_id 1 store_id 1 queue_id 0 item_uin 12 ，，在consumer0和consumer2都有输出

这个问题像是三个consumer_server.X.conf的shm_key_base相同的情况，是之前sample配置有误引起的，建议按 c89958854a0b67d19843c2c5d89a02791b9e060c 修改配置，或者 pull 最新代码和配置。如果仍有问题，麻烦打包日志到 phxteam@tencent.com。

**Comment by tinyshu** [comment]
@unixliang 不是 我的配置已经是pull的最新的

**Comment by unixliang** [comment]
```shm_key_base``` 修改后要重启consumer哦。
建议打包日志到phxteam@tencent.com，我们看看。
