### ISSUE TITLE
breakpoint.h 里边各个类的成员函数在哪儿实现呢?

### ISSUE THREAD

**Issue by TingkaiH** [Tencent/phxqueue#32]
该项目是完全开源的吗？

**Comment by unixliang** [comment]
breakpoint是用来做监控的，但是各使用者的监控体系不一样，无法统一，所以这里需要使用者重载breakpoint来实现自己的监控逻辑。
目前我们内部使用的phxqueue版本和git上的一致，但是为了监控我们也重载并实现了自己breakpoint。
