### ISSUE TITLE
一对多关系如何配置

### ISSUE THREAD

**Issue by tinyshu** [Tencent/phxqueue#33]
一个消费者发送的消息，会被每个消费者消费后这个配置关系

**Comment by tinyshu** [comment]
已经配置好了：）

**Comment by taohex** [comment]
你好，请参考[队列配置示例：多订阅](https://github.com/Tencent/phxqueue/wiki/PhxQueue%E9%85%8D%E7%BD%AE#17-%E9%98%9F%E5%88%97%E9%85%8D%E7%BD%AE%E7%A4%BA%E4%BE%8B%E5%A4%9A%E8%AE%A2%E9%98%85)

**Comment by tinyshu** [comment]
试了可以 ，还有个问题 ，2个sonsume，，我关闭一个sonsumeB然后让生产者发送一个消息，这个消息被一个consume消费后，在启动那个关闭的sonsumeB，这个sonsumeB读取不到消息，设计是这样的吧

**Comment by unixliang** [comment]
> 试了可以 ，还有个问题 ，2个sonsume，，我关闭一个sonsumeB然后让生产者发送一个消息，这个消息被一个consume消费后，在启动那个关闭的sonsumeB，这个sonsumeB读取不到消息，设计是这样的吧

只有一个订阅的场景下，这个现象符合预期，在多订阅场景下则不是。

下面才是正确的echo多订阅场景：

(producer console)
![image](https://user-images.githubusercontent.com/3634922/30893288-f8632730-a36f-11e7-85ce-a68ad3e06ba8.png)

(consumer 0 console)
![image](https://user-images.githubusercontent.com/3634922/30893291-0006ff84-a370-11e7-9d8f-8c4ba0aa44e5.png)

(consumer 1 console)
![image](https://user-images.githubusercontent.com/3634922/30893297-069b6a92-a370-11e7-82d7-f9cc380aa1de.png)

(consumer 2 console)
![image](https://user-images.githubusercontent.com/3634922/30893309-0c4fa0ca-a370-11e7-84f7-025080e40d6d.png)

可以看到一条消息被消费了两次。

**Comment by unixliang** [comment]
@tinyshu 请参考 4416e43b3df53e308c1cd810b61a7e175d726adc 修改配置后再尝试，看能否得到上面的结果。
