### ISSUE TITLE
MQ客户端使用问题

### ISSUE THREAD

**Issue by Jerryang** [Tencent/phxqueue#34]
有几个问题：
1. 是否支持C++之外的语言？（微信的系统里，非C++的系统如何接入？）
2. 生产者和消费者，是否需要额外编程才能够使用？(类似test里的SimpleConsumer和SimpleProducer)？
3. 有无节点crash时，failover的时间的数据?（可以以同机房多个交换机下的网络环境为例）？
4. 希望提供更多使用上的Demo(生产者/消费者 & PTP/TOPIC)，方便大家更便利的进行测试(这是后续深入测试和研究的基础)。

辛苦不忙时予以解答。

**Comment by unixliang** [comment]
你好，

> 是否支持C++之外的语言？（微信的系统里，非C++的系统如何接入？）

暂时不支持C++之外的语言，我们正在做多语言支持。
但微信内部的接入并非只有C++系统，原因下述。

> 生产者和消费者，是否需要额外编程才能够使用？(类似test里的SimpleConsumer和SimpleProducer)？

目前的开源版本，需要在Consumer做额外编程才能投产。做法类似```phxqueue_phxrpc/test/echo_handler.cpp```，实现自己的Handler，自定义消费逻辑。
为了降低使用门槛，我们会实现一个默认Handler，逻辑是通过http将数据发送到订阅方。这样也能顺带支持多语言（通过http协议屏蔽语言差异），微信内部也有这样的使用案例。

> 有无节点crash时，failover的时间的数据?（可以以同机房多个交换机下的网络环境为例）？

failover的时长与租约时长正相关，Store默认的Master租约时长是5s，也就是说failover时长也是5s左右。

> 希望提供更多使用上的Demo(生产者/消费者 & PTP/TOPIC)，方便大家更便利的进行测试(这是后续深入测试和研究的基础)。

目前文档还是相对缺乏。我们会针对更多的使用场景给出demo，例如：

DONE: [1.7 队列配置示例：多订阅](https://github.com/Tencent/phxqueue/wiki/PhxQueue%E9%85%8D%E7%BD%AE#17-%E9%98%9F%E5%88%97%E9%85%8D%E7%BD%AE%E7%A4%BA%E4%BE%8B%E5%A4%9A%E8%AE%A2%E9%98%85)
TODO: [1.8 队列配置示例：多级重试](https://github.com/Tencent/phxqueue/wiki/PhxQueue%E9%85%8D%E7%BD%AE#18-%E9%98%9F%E5%88%97%E9%85%8D%E7%BD%AE%E7%A4%BA%E4%BE%8B%E5%A4%9A%E7%BA%A7%E9%87%8D%E8%AF%95)

**Comment by Jerryang** [comment]
“我们会实现一个默认Handler，逻辑是通过http将数据发送到订阅方。这样也能顺带支持多语言（通过http协议屏蔽语言差异），微信内部也有这样的使用案例。”
有考虑提供基于使用二进制传输协议的各个语言的SDK么。HTTP效率实在是太低了。
另外，能否提供一些微信内部在稳定运行的常见Consumer和Producer实现，例如，用于严格保序场景的，用于高吞吐场景的，用于At least one以及At most one场景的一些靠谱的实现。

谢谢。

**Comment by unixliang** [comment]
> 有考虑提供基于使用二进制传输协议的各个语言的SDK么。HTTP效率实在是太低了。

我们正考虑基于[phxrpc](https://github.com/Tencent/phxrpc)自动生成各语言SDK，预期工作量大不会太快推出。
其实HTTP的效率问题主要在于短链，这个可以keep-alive解决。用HTTP来屏蔽各语言差异，比起直接生成各语言SDK，成本更低，所以我们更倾向这样做。

> 另外，能否提供一些微信内部在稳定运行的常见Consumer和Producer实现，例如，用于严格保序场景的，用于高吞吐场景的，用于At least one以及At most one场景的一些靠谱的实现。

phxqueue能同时满足数据可靠、有序、高吞吐、At least one，所以业务不需要根据业务场景来选择或牺牲任何一个特性。不过At most one目前是无能为力了。

另外，在微信内部，业务接入phxqueue，一般不需要定制实现，也不用怎么写代码：
* Producer只是一个入队API，是通用的。--业务调用入队API的代码还是要写的
* 如上所述，我们在Consumer中注册了一个通用Handler，通过RPC的方式发送数据到订阅方，所以订阅方只要提供RPC服务就能接收数据。--这里业务只需要把自己的服务写好就行了，不需要写和队列有关的代码
* 只有少部分较复杂的业务，想在Consumer自定义消费逻辑，才会注册自己写的Handler。
