### ISSUE TITLE
出入队严格有序问题

### ISSUE THREAD

**Issue by tinyshu** [Tencent/phxqueue#35]
出入队严格有序是 比如生产者发送2个消息A ，B,,先发送A在发送B
但是网络或者其他原因导致B先到达store的队列里，这样那一个消息会被先消费了

**Comment by unixliang** [comment]
你好，
生产者发出A后，在收到A的回包前发送B，这样A和B是并行发送，没有因果关系，在分布式系统无法定义谁先谁后；
只有生产者在收到A的入队成功的回包后再发送B，才能确定A比B先被消费。

**Comment by tinyshu** [comment]
好的
