### ISSUE TITLE
make的时候报错，请问怎么回事

### ISSUE THREAD

**Issue by miracle2lee** [Tencent/phxqueue#37]
phxqueue_phxrpc/test/consumer_main.cpp: In function 'int main(int, char**)':
phxqueue_phxrpc/test/consumer_main.cpp:60:28: error: 'phxrpc::ServerUtils' has not been declared
     if (daemonize) phxrpc::ServerUtils::Daemonize();
                            ^
phxqueue_phxrpc/test/consumer_main.cpp:109:5: error: 'closelog' is not a member of 'phxrpc'
     phxrpc::closelog();
     ^
phxqueue_phxrpc/test/consumer_main.cpp:109:5: note: suggested alternative:
In file included from /usr/include/syslog.h:1:0,
                 from /home/ubuntu/phxqueue//third_party/phxrpc/phxrpc/file/log_utils.h:25,
                 from /home/ubuntu/phxqueue//third_party/phxrpc/phxrpc/file.h:25,
                 from /home/ubuntu/phxqueue//third_party/phxrpc/phxrpc/rpc/server_config.h:26,
                 from /home/ubuntu/phxqueue//third_party/phxrpc/phxrpc/rpc.h:25,
                 from phxqueue_phxrpc/test/consumer_main.cpp:26:
/usr/include/x86_64-linux-gnu/sys/syslog.h:175:13: note:   'closelog'
 extern void closelog (void);
             ^
make: *** [phxqueue_phxrpc/test/consumer_main.o] Error 1

**Comment by unixliang** [comment]
请严格按照README的build步骤试试，或者提供更详细的信息，例如环境、重现步骤。
