### ISSUE TITLE
bash build.sh 报错

### ISSUE THREAD

**Issue by Hadesu** [Tencent/phxqueue#39]
+ autoreconf -f -i -Wall,no-obsolete
./autogen.sh: 43: ./autogen.sh: autoreconf: not found
./autoinstall.sh: line 122: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
./autoinstall.sh: line 84: cd: protobuf: No such file or directory
protobuf install fail. please check compile error info.

**Comment by unixliang** [comment]
请安装automake后再试试
