### ISSUE TITLE
phxqueue docker tag was empty.

### ISSUE THREAD

**Issue by wangxingge** [Tencent/phxqueue#4]
Issue as my title.
phxqueue docker tag was empty.

I executed cmd docker pull phxqueue/phxqueue with an issue: manifest for phxqueue/phxqueue:latest not found.

Then i check the tag of phxqueue, its empty...... :(

**Comment by taohex** [comment]
You can [build image by your self](https://github.com/Tencent/phxqueue/wiki/Quickstart-with-Docker) right now. Docker hub image will be ready soon, Thanks!

**Comment by taohex** [comment]
Docker hub image released! Please to [Quickstart with Docker](https://github.com/Tencent/phxqueue/wiki/Quickstart-with-Docker)

**Comment by wangxingge** [comment]
thanks for release docker image, i'd love to use docker, that's avoid lots deployment issue.
