### ISSUE TITLE
make[1]: *** 没有规则可以创建“test_propose_batch”需要的目标“test_propose_batch.o”。 停止 

### ISSUE THREAD

**Issue by yutaoli** [Tencent/phxqueue#40]
**操作**
cd $PHXPAXOS_DIR
./autoinstall.sh &&  make -j $kernal_num  && make install

**报错**
error: make[1]: *** 没有规则可以创建“test_propose_batch”需要的目标“test_propose_batch.o”。 停止。

**我的临时解决方法**
查看makefile，干掉这个文件的编译。

**我的疑问**
这是bug么？如果不是，那么有没有更好的解决方法？
如果是，什么时候修复呢？

**Comment by unixliang** [comment]
已fixed。
