### ISSUE TITLE
PhxQueue可以用于跨大洲的消息队列吗？如果可以，性能和实时性如何？

### ISSUE THREAD

**Issue by yurongliao** [Tencent/phxqueue#42]
PhxQueue可以用于跨大洲的消息队列吗？如果可以，性能和实时性如何？

**Comment by desmondck** [comment]
底层基于paxos，在跨洲情况下，远端可用于做热备，store的主要保证始终在近端。满足这两个场景下，性能应该不会出现明显下降。

**Comment by unixliang** [comment]
phxqueue对跨洲的场景很友好，原因是入队端和出队端没有共同依赖，可以分别部署在不同洲。具体部署方式是，produer、store部署在A州，consumer、scheduler、lock部署在B洲。其中只有consumer到store的访问存在跨洲通讯，但因为这里是批量拉取，所以跨洲不会对吞吐做成太大影响。

作为对比，Kafka的各模块需要共同依赖同一个zk，所以入队端和出队端只能部署在同城，只能以MirrorMaker的方式做跨洲镜像同步。
