### ISSUE TITLE
启动store_server 报错

### ISSUE THREAD

**Issue by huangxiaowei99** [Tencent/phxqueue#46]
bin/store_main -c etc/store_server.0.conf
ERR: MakeArgs ret -1

日志如下：
Log file created at: 2018/01/04 19:11:30
Running on machine: iZ8vbcyspccwhdj71zlryfZ
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0104 19:11:30.279340 19092 logger_google.cpp:79] ^[[41;37m ERR: PN15phxqueue_phxrpc6config10BaseConfigIN8phxqueue6config12GlobalConfigEEE::LoadFile:36 FileConfig::Read fail. file ./etc/globalconfig.conf ^[[0m
E0104 19:11:30.279722 19092 logger_google.cpp:79] ^[[41;37m ERR: PN8phxqueue5store5StoreE::InitTopicID:79 GetTopicIDByTopicName ret -10102 topic test ^[[0m
E0104 19:11:30.279737 19092 logger_google.cpp:79] ^[[41;37m ERR: PN8phxqueue5store5StoreE::Init:144 InitTopicID ret -10102 topic test ^[[0m
E0104 19:11:30.279744 19092 logger_google.cpp:79] ^[[41;37m ERR: MakeArgs:66 init phxqueue store err ^[[0m

查看配置没有什么问题

**Comment by unixliang** [comment]
68547166dbbbb581d4b7986bd5920ba650550050 已fix，多谢反馈：）
