### ISSUE TITLE
Branch master sha1 df6c8de, git submodule phxrpc did not contain a1b7ce5c5ae633bac3d9df85ee874a1e8a82d353

### ISSUE THREAD

**Issue by JackDrogon** [Tencent/phxqueue#52]
Branch master sha1 df6c8de, Fetched in submodule path 'third_party/phxrpc', but it did not contain a1b7ce5c5ae633bac3d9df85ee874a1e8a82d353. Direct fetching of that commit failed.

**Comment by unixliang** [comment]
we will fix it later.

**Comment by unixliang** [comment]
#54 fixed. Thx for reminding.
