### ISSUE TITLE
为什么已经是Paxos数据同步了，还要同步刷盘呢

### ISSUE THREAD

**Issue by triompha** [Tencent/phxqueue#6]
如题

**Comment by unixliang** [comment]
你好，
这里有两点考虑：
1. 异步刷盘最直观的问题是，多数节点故障（机器重启/硬盘故障），就可能会丢数据。
2. 要做一套针对交易系统的可靠组件，需要考虑各种极端异常情况，身为工程师不一定能考虑周全；而 Paxos 协议的正确运行，加上简单的拜占庭错误检查手段，就能避免这些异常带来的数据不一致，这是有数学证明的；其中 Paxos 协议的正确运行需要同步刷盘。

所以，在不牺牲性能的前提下，用同步刷盘进一步提高数据可靠性，何乐而不为呢？

**Comment by desmondck** [comment]
说白了，phxpaxos协议实现本身就要求同步刷盘保证正确性，因此，基于phxpaxos的实现也是同步的。
