### ISSUE TITLE
glog对unwind依赖问题

### ISSUE THREAD

**Issue by oujiangping** [Tencent/phxqueue#7]
编译过程中编译到test模块的时候发现以下问题
utilities.cc:(.text+0x867): undefined reference to `_Ux86_64_getcontext'
utilities.cc:(.text+0x880): undefined reference to `_ULx86_64_init_local'
utilities.cc:(.text+0x8ec): undefined reference to `_ULx86_64_get_reg'
utilities.cc:(.text+0x949): undefined reference to `_ULx86_64_step'

原因是glog中依赖了unwind，在makefile.mk的LDFLAGS加unwind解决了。

**Comment by unixliang** [comment]
感谢反馈：）
引起这个问题的原因是：glog编译时依赖了unwind动态库，而phxqueue只依赖了glog静态库。
