### ISSUE TITLE
[root@localhost phxqueue]# bin/store_main -c etc/store_server.0.conf ERR: MakeArgs ret -1

### ISSUE THREAD

**Issue by shangmacun** [Tencent/phxqueue#8]
[root@localhost phxqueue]# bin/store_main -c etc/store_server.0.conf
ERR: MakeArgs ret -1

**Comment by taohex** [comment]
Please paste the log in `log/store.0/store_main.INFO`

**Comment by shangmacun** [comment]
Log file created at: 2017/09/14 04:07:15
Running on machine: localhost.localdomain
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0914 04:07:15.580317 29020 logger_google.cpp:79] ^[[41;37m ERR: PN8phxqueue5store8SyncCtrlE::Init:90 open err Is a directory path ./data/store.0/sync ^[[0m
E0914 04:07:15.583386 29020 logger_google.cpp:79] ^[[41;37m ERR: PN8phxqueue5store5StoreE::Init:163 sync Init ret -1 ^[[0m
E0914 04:07:15.583400 29020 logger_google.cpp:79] ^[[41;37m ERR: MakeArgs:66 init phxqueue store err ^[[0m

**Comment by shangmacun** [comment]
./data/store.0  need to create manually?

**Comment by shangmacun** [comment]
此条语句报错
    auto sync_path(opt->data_dir_path + "/sync");
    int fd = open(sync_path.c_str(), O_RDWR | O_CREAT, S_IRUSR | S_IWUSR);
    if (fd < 0) {
        QLErr("open err %s path %s", strerror(errno), sync_path.c_str());
        return comm::RetCode::RET_ERR_SYS;
    }

**Comment by taohex** [comment]
请更新到最新版本，会自动创建所有需要的目录，谢谢反馈！
